# encoding: ascii-8bit

# Copyright 2022 Ball Aerospace & Technologies Corp.
# All Rights Reserved.
#
# This program is free software; you can modify and/or redistribute it
# under the terms of the GNU Affero General Public License
# as published by the Free Software Foundation; version 3 with
# attribution addendums as found in the LICENSE.txt
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.

# Modified by OpenC3, Inc.
# All changes Copyright 2022, OpenC3, Inc.
# All Rights Reserved
#
# This file may also be used under the terms of a commercial license
# if purchased from OpenC3, Inc.

version: "3.5"

networks:
  default:
    name: openc3-cosmos-network

services:
  openc3-minio:
    image: "${OPENC3_REGISTRY}/openc3inc/openc3-minio:${OPENC3_TAG}"
    # Uncomment to run unit tests against the minio server
    # ports:
    #   - "127.0.0.1:9000:9000"
    volumes:
      - "openc3-minio-v:/data"
      - "./cacert.pem:/devel/cacert.pem:z"
    command: server --address ":9000" --console-address ":9001" /data
    restart: "unless-stopped"
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      MINIO_ROOT_USER: "${OPENC3_BUCKET_USERNAME}"
      MINIO_ROOT_PASSWORD: "${OPENC3_BUCKET_PASSWORD}"
      # Domain doesn't really matter but it's required. We really want the /minio path.
      # This is handled by our traefik configuration via rule: PathPrefix(`/minio`)
      # and forwarded on to the console at http://openc3-minio:9001
      MINIO_BROWSER_REDIRECT_URL: "http://openc3.com/minio"
      SSL_CERT_FILE: "/devel/cacert.pem"
      CURL_CA_BUNDLE: "/devel/cacert.pem"
      REQUESTS_CA_BUNDLE: "/devel/cacert.pem"
      NODE_EXTRA_CA_CERTS: "/devel/cacert.pem"

  openc3-redis:
    image: "${OPENC3_REGISTRY}/openc3inc/openc3-redis:${OPENC3_TAG}"
    volumes:
      - "openc3-redis-v:/data"
      - "./cacert.pem:/devel/cacert.pem:z"
      - "./openc3-redis/users.acl:/config/users.acl:z"
    restart: "unless-stopped"
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      SSL_CERT_FILE: "/devel/cacert.pem"
      CURL_CA_BUNDLE: "/devel/cacert.pem"
      REQUESTS_CA_BUNDLE: "/devel/cacert.pem"
      NODE_EXTRA_CA_CERTS: "/devel/cacert.pem"

  openc3-redis-ephemeral:
    image: "${OPENC3_REGISTRY}/openc3inc/openc3-redis:${OPENC3_TAG}"
    volumes:
      - "./cacert.pem:/devel/cacert.pem:z"
      - "./openc3-redis/users.acl:/config/users.acl:z"
    restart: "unless-stopped"
    command: [ "redis-server", "/config/redis_ephemeral.conf" ]
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      SSL_CERT_FILE: "/devel/cacert.pem"
      CURL_CA_BUNDLE: "/devel/cacert.pem"
      REQUESTS_CA_BUNDLE: "/devel/cacert.pem"
      NODE_EXTRA_CA_CERTS: "/devel/cacert.pem"

  openc3-cosmos-cmd-tlm-api:
    image: "${OPENC3_REGISTRY}/openc3inc/openc3-cosmos-cmd-tlm-api:${OPENC3_TAG}"
    restart: "unless-stopped"
    depends_on:
      - "openc3-redis"
      - "openc3-redis-ephemeral"
      - "openc3-minio"
    volumes:
      - "openc3-gems-v:/gems"
      - "./plugins:/plugins:z"
      - "./cacert.pem:/devel/cacert.pem:z"
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      - "RAILS_ENV=production"
      - "GEM_HOME=/gems"
    group_add:
      - ${OPENC3_LOCAL_MODE_GROUP_ID}
    env_file:
      - ".env"

  openc3-cosmos-script-runner-api:
    image: "${OPENC3_REGISTRY}/openc3inc/openc3-cosmos-script-runner-api:${OPENC3_TAG}"
    restart: "unless-stopped"
    depends_on:
      - "openc3-redis"
      - "openc3-redis-ephemeral"
      - "openc3-minio"
    volumes:
      - "openc3-gems-v:/gems:ro"
      - "./plugins:/plugins:z"
      - "./cacert.pem:/devel/cacert.pem:z"
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      - "RAILS_ENV=production"
      - "GEM_HOME=/gems"
    group_add:
      - ${OPENC3_LOCAL_MODE_GROUP_ID}
    env_file:
      - ".env"

  openc3-operator:
    image: "${OPENC3_REGISTRY}/openc3inc/openc3-operator:${OPENC3_TAG}"
    restart: "unless-stopped"
    depends_on:
      - "openc3-redis"
      - "openc3-redis-ephemeral"
      - "openc3-minio"
    volumes:
      - "openc3-gems-v:/gems:ro"
      - "./plugins:/plugins:z"
      - "./cacert.pem:/devel/cacert.pem:z"
      # Add access to the entire C drive on Windows
      # - "/c:/c"
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      - "GEM_HOME=/gems"
    group_add:
      - ${OPENC3_LOCAL_MODE_GROUP_ID}
    env_file:
      - ".env"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
     - "20000-20999:20000-20999"

  openc3-traefik:
    image: "${OPENC3_REGISTRY}/openc3inc/openc3-traefik:${OPENC3_TAG}"
    volumes:
      - "./cacert.pem:/devel/cacert.pem:z"
      - "./openc3-traefik/traefik.yaml:/etc/traefik/traefik.yaml:z"
      # - "./openc3-traefik/traefik-allow-http.yaml:/etc/traefik/traefik.yaml:z"
      # - "./openc3-traefik/traefik-ssl.yaml:/etc/traefik/traefik.yaml:z"
      # - "./openc3-traefik/traefik-letsencrypt.yaml:/etc/traefik/traefik.yaml:z"
      # - "./openc3-traefik/cert.key:/etc/traefik/cert.key:z"
      # - "./openc3-traefik/cert.crt:/etc/traefik/cert.crt:z"
    ports:
      #- "2900:80"
      #- "2943:443"
      - "80:80"
      - "443:443"
    restart: "unless-stopped"
    depends_on:
      - "openc3-redis"
      - "openc3-redis-ephemeral"
      - "openc3-minio"
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      SSL_CERT_FILE: "/devel/cacert.pem"
      CURL_CA_BUNDLE: "/devel/cacert.pem"
      REQUESTS_CA_BUNDLE: "/devel/cacert.pem"
      NODE_EXTRA_CA_CERTS: "/devel/cacert.pem"

  openc3-cosmos-init:
    image: "${OPENC3_REGISTRY}/openc3inc/openc3-cosmos-init:${OPENC3_TAG}"
    restart: on-failure
    depends_on:
      - "openc3-traefik"
      - "openc3-redis"
      - "openc3-redis-ephemeral"
      - "openc3-minio"
    volumes:
      - "openc3-gems-v:/gems"
      - "./plugins:/plugins:z"
      - "./cacert.pem:/devel/cacert.pem:z"
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      - "GEM_HOME=/gems"
    group_add:
      - ${OPENC3_LOCAL_MODE_GROUP_ID}
    env_file:
      - ".env"

volumes:
  openc3-redis-v: {}
  openc3-minio-v: {}
  openc3-gems-v: {}
